### ISSUE TITLE
Windows issue

### ISSUE THREAD

**Issue by kkoomen** [thinca/action-setup-vim#12]
Hi,

Thanks for the awesome plugin, I use it a lot for my own plugin testing!

Have a look at my action: https://github.com/kkoomen/vim-doge/actions/runs/5499186462/jobs/10021206608

It did fail for vim v7.4.2119, where as the head vim version doesn't seem to have a problem. Can you fix the issue?

<img width="761" alt="image" src="https://github.com/thinca/action-setup-vim/assets/10693490/b1ae162c-df30-4e71-8212-778a0d21e802">

**Comment by thinca** [comment]
I released [v2.1.0](https://github.com/thinca/action-setup-vim/releases/tag/v2.1.0).
This version can setup Vim v7.4 on Windows.
