### ISSUE TITLE
Node 16 is deprecated

### ISSUE THREAD

**Issue by hattya** [thinca/action-setup-vim#13]
### Describe the bug

Node 16 is deprecated and has to update to Node 20.

ref: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

### How to reproduce the problem

Always.

### Expected behavior

This action is run on Node 20.

### Actual behavior

A warning is displayed as follow:

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: thinca/action-setup-vim@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by thinca** [comment]
I released v2.0.0.  Thank you.
https://github.com/thinca/action-setup-vim/releases/tag/v2.0.0
