### ISSUE TITLE
v1.0.6 is not released

### ISSUE THREAD

**Issue by hattya** [thinca/action-setup-vim#3]
### Describe the bug

v1.0.5 was re-released as v1.0.6, v1.0, and v1.

### How to reproduce the problem

By https://github.com/thinca/action-setup-vim/actions/runs/342006295, it was ran on v1.0.5.

### Expected behavior

`thinca/action-setup-vim@v1` builds older Vim versions on macOS.

### Actual behavior

`thinca/action-setup-vim@v1` fails to build older Vim versions on macOS.

**Comment by thinca** [comment]
Oh, that's true.  Thank you for reporting!
I re-released (new tags pushed) v1.0.6.
Would you check it?

**Comment by hattya** [comment]
It works!
